---
title: "Project1"
---

```{r setup}
data=read.csv('COVID-19_project1.csv',header=TRUE)
newdata = data[, -c(1:3, 7)]
newdata$sex <- ifelse(newdata[,2]=="Female", 1, 0)
newdata$hosp_yn <- ifelse(newdata[,4]=="Yes", 1, 0)
newdata$icu_yn <- ifelse(newdata[,5]=="Yes", 1, 0)
newdata$death_yn <- ifelse(newdata[,6]=="Yes", 1, 0)
newdata$medcond_yn <- ifelse(newdata[,7]=="Yes", 1, 0)
newdata$current_status <- ifelse(newdata[,1]=="Laboratory-confirmed case", 1, 0)

newdata <- newdata[!newdata$age_group =="Unknown",]

for(i in 1: 236406)
{
  if(newdata$age_group[i] =="0 - 9 Years"){
    newdata$age_group[i] = 0
}    

if(newdata$age_group[i] =="10 - 19 Years"){
    newdata$age_group[i] = 1
} 

if(newdata$age_group[i] =="20 - 29 Years"){
    newdata$age_group[i] = 2
} 
    
if(newdata$age_group[i] =="30 - 39 Years"){
    newdata$age_group[i] = 3
} 
    
 if(newdata$age_group[i] =="40 - 49 Years"){
    newdata$age_group[i] = 4
 }
    
if(newdata$age_group[i] =="50 - 59 Years"){
    newdata$age_group[i] = 5
} 
    
if(newdata$age_group[i] =="60 - 69 Years"){
    newdata$age_group[i] = 6
}
    
if(newdata$age_group[i] =="70 - 79 Years"){
    newdata$age_group[i] = 7
} 
  
if(newdata$age_group[i] =="80+ Years")  
  newdata$age_group[i] =  8
  }  

```

```{r}
library(glmnet)
lr = glm(death_yn ~ ., family = "binomial", data=newdata)
summary(lr)

index=sample(1:nrow(newdata), round(nrow(newdata)*0.7))
train=newdata[index, ]
test=newdata[-index, ]

cor(train[, -3])

lr2 = glm(death_yn ~ icu_yn , family = "binomial", data=train)
summary(lr2)

lr3 = glm(death_yn ~ hosp_yn , family = "binomial", data=train)
summary(lr3)

lr4 = glm(death_yn ~ age_group , family = "binomial", data=train)
summary(lr4)


glm.probs=predict(lr2, test,type="response")
glm.pred=rep(0, 70922)
glm.pred[glm.probs>.5]= 1
table(glm.pred,test[,6])

glm.probs2=predict(lr3, test,type="response")
glm.pred2=rep(0, 70922)
glm.pred2[glm.probs2>.5]= 1
table(glm.pred2,test[,6])

glm.probs3=predict(lr, test,type="response")
glm.pred3=rep(0, 70922)
glm.pred3[glm.probs3>.5]= 1
table(glm.pred3,test[,6])

glm.probs4=predict(lr4, test,type="response")
glm.pred4=rep(0, 70922)
glm.pred4[glm.probs4>.5]= 1
table(glm.pred4,test[,6])
```
With all predictors: 92.5% 

Icu: 91.5% 

Hospitalized: 89.7% 

In general, predicted not-dead (death_yn = 0) correctly significantly better than if dead (death_yn = 1)


```{r}
library(class)
knn.prediction = knn.pred=knn(train[,-6], test[,-6] ,train[,6],k=25)
table(knn.pred, test[,6])
```


```{r}
library(class)....
knn.data = rep(0,2364)

for(i in 1:2364){
knn.pred=knn(train[,-6], test[,-6] ,train[,6],k=i)
knn.data[i] = mean(knn.pred==test[,6])
}
which.max(knn.data)
```